replicaCount: 1
image:
  repo: "vudinhdai2505/telegraf"
  tag: "v5"
  pullPolicy: Always
namespace: monitoring

label:
  name: telegraf
  instance: telegraf

serviceAccountName: telegraf

resources: {}
env:
  - name: CLUSTER_NAME
    value: "FKE"
  - name: PROMETHEUS_URL
    value: "http://10.0.0.13:31365"
  - name: USER_NAME
    value: ""
  - name: PASSWORD
    value: ""


