apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-key
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson